### ISSUE TITLE
IHubContent should have metadata, and provide a way to fetch it

### ISSUE THREAD

**Issue by tomwayson** [Esri/hub.js#353]
follow up from #330 and related to #322 (but more limited in scope).

As I indicated in https://github.com/Esri/hub.js/issues/322#issuecomment-685131319, I think `getContent()` should return `metadata` when it exists (i.e. when fetching from the Hub API). I'm not sure that it should proactively make an async request to get it otherwise. We can start by adding something like `getContentMetadata()` that would fetch it from wherever the enrichment currently fetches it from and the client can call that as needed.

**Comment by drewctate** [comment]
@tomwayson This may be the key: https://www.arcgis.com/sharing/rest/content/items/d9ea4896eb7b4471b6839771c51de091/info/metadata/metadata.xml

**Comment by drewctate** [comment]
Even better: https://www.arcgis.com/sharing/rest/content/items/1ce4060e854747038b153c5c8f8c894d/info/metadata/metadata.xml

**Comment by ajturner** [comment]
This is a good plan. However, please be aware that the purpose of `getContent()` and other Hub.js functions is to provide a clear, consistent interface to the Hub models. it's not just a wrapper for promise chains :)

Specifically, in the near future item editors will be able to configure their metadata display. By far the most common request is to choose what shows in "Last Updated" because it's often not the "ArcGIS Item edited date" but instead some real-world date when a surveyor went into the field. Therefore, the [`Content.publishedDate`](https://github.com/Esri/hub.js/blob/fbfcf0ddb74a2dad215583163b44f530f0e38e03/packages/common/src/types.ts#L256) may be coming from `Content.publishedDateSource = 'metadata.dataIdInfo.idCitation.date.pubDate'` such as from [DC Trees](https://www.arcgis.com/sharing/rest/content/items/f6c3c04113944f23a7993f2e603abaf2/info/metadata/metadata.xml). 

So the `getContent()` call will look at it's display configuration (likely in either `item.properties` or another sidecar in resources) to know it should fetch this information and merge specific results into the core content model. @tomwayson @drewctate @mikeringrose

**Comment by tomwayson** [comment]
Looks like the hub-indexer uses https://www.npmjs.com/package/fast-xml-parser to parse the metadata XML response, and it looks like we can use that in a browser and [it's only 5.5kB gzipped]( https://bundlephobia.com/result?p=fast-xml-parser), so I'll plan to implement this using that library. The parser is [configured here](https://github.com/ArcGIS/hub-indexer/blob/e86f06d46ac8a604313b0e925c02a148bd31bef4/packages/duke/utils/request.js#L9-L14).

**Comment by tomwayson** [comment]
relies on https://github.com/Esri/arcgis-rest-js/issues/738
