### ISSUE TITLE
Would like to be able to convert IModel into Content

### ISSUE THREAD

**Issue by andrewctate** [Esri/hub.js#417]
What if `getContent` could accept an `IModel` as well as an item id? It would just have to be smart enough not to request things from the API that it didn't have to, but still get the goodies and extras that can't be gleaned from the IModel.

**Comment by tomwayson** [comment]
This is a good idea. I've thought about having it accept an `IItem`. 

Do you think it's common scenario where we have the `item` _and_ the `data`?

**Comment by tomwayson** [comment]
related to #415

**Comment by drewctate** [comment]
@tomwayson 
> Do you think it's common scenario where we have the item and the data before we want to call getContent()
That is nearly every scenario I've run into so far. But, I recognize that I've focused on initiative and solution templates so it would be wise to do a broader poll.

**Comment by andrewctate** [comment]
[POA]
- Change `getContent` call signature to accept an `IItem` or an `IModel` `getContent(idOrObj: IModel | IItem | string...)` [here](https://github.com/Esri/hub.js/blob/master/packages/content/src/content.ts#L71)
- Extract item and data objects from `idOrObj` as available
- If item object is available, always use `getContentFromPortal`
- change `getContentFromPortal`
     - relax call signature to allow an item to be passed instead of an id: `getContentFromPortal(idOrItem: string | IItem,  requestOptions?: IHubRequestOptions)`
     - use item object when provided instead of requesting a new one from Portal API
- If an `IModel` was provided, and `shouldFetchData` is true, register a function that resolves to a copy of the provided `model.data` hash instead of `getContentData` [here](https://github.com/Esri/hub.js/blob/master/packages/content/src/content.ts#L93)

cc: @tomwayson

**Comment by mikeringrose** [comment]
> [POA]
> 
> * Change `getContent` call signature to accept an `IItem` or an `IModel` `getContent(idOrObj: IModel | IItem | string...)` [here](https://github.com/Esri/hub.js/blob/master/packages/content/src/content.ts#L71)
> * Extract item and data objects from `idOrObj` as available
> * If item object is available, always use `getContentFromPortal`
> * change `getContentFromPortal`
>   
>   * relax call signature to allow an item to be passed instead of an id: `getContentFromPortal(idOrItem: string | IItem,  requestOptions?: IHubRequestOptions)`
>   * use item object when provided instead of requesting a new one from Portal API
> * If an `IModel` was provided, and `shouldFetchData` is true, register a function that resolves to a copy of the provided `model.data` hash instead of `getContentData` [here](https://github.com/Esri/hub.js/blob/master/packages/content/src/content.ts#L93)
> 
> cc: @tomwayson

1) why not just require an IModel since if you have Item, you just do `{ item }`?
2) do we really expect a client to not know the type that they have? why not have `getContentById` and `getContent` and be explicit in our actions.
3) why relax the call signature? why not just be explicit and not increase the cyclomatic complexity of `getContentFromPortal` (no additional if checks)

Sorry just trying to understand the thinking here. A lot of these methods seem overly complex, but that could just be me not understanding.

**Comment by andrewctate** [comment]
@mikeringrose thanks for the input!

> A lot of these methods seem overly complex

Do you mean the current utils or my suggestions (or both)?

> why not just require an IModel since if you have Item, you just do { item }?

Good point. The I-can-accept-three-things call signature felt smelly.

> do we really expect a client to not know the type that they have? why not have getContentById and getContent and be explicit in our actions.

We have some precedent for a call signature that can accept an id or a model ([see here](https://github.com/Esri/hub.js/blob/0d138c678a5337feacf6fc13c694d8505f6877e0/packages/sites/src/unlink-site-and-page.ts#L22)) so I think that probably got me thinking that way. I'd be interested to hear @tomwayson's thinking since he had a [similar thought](https://github.com/Esri/hub.js/issues/417#issuecomment-718889324).

But, I do think we can expect the client to know, so bifurcating into two entry points could work. It sounds like you think it would be better to push the responsibility to the client in order to simplify this flow(?) In that case we'd probably
1. rename the current `getContent` function to `getContentById`
2. create a new `getContent` function that accepts an `IModel`
3. Somehow create a way to invoke the `getContentFromPortal` flow without triggering a network request. Either 
    - compromise and allow `getContentFromPortal` to accept an `IModel` or an ID
    - similarly create two versions of the `getContentFromPortal` function, one that accepts and ID and one that accepts an `IModel`
3. split [these lines](https://github.com/Esri/hub.js/blob/master/packages/content/src/content.ts#L90-L102) from the existing `getContent` function into their own `enrichContent` function that can be used at the end of both branches (`getContentById` and `getContent`).

Am I understanding you?

**Comment by tomwayson** [comment]
re: `getContent` and `getContentById` - that would be a breaking change. I think consumers will almost always know what they have, but it is one more `import` if they need to do both. I'm not opposed to it, but as @andrewctate says, it's consistent w/ the signatures of other existing functions. In at least two of those cases, I moved that "if id, then this, otherwise, that" logic from multiple places in the app. In other words, there was a reason to have the hub.js functions handle that rather than have the logic in duplicate places in the app.

To some extent this boils down to code style. Our current style is to use less fns w/ more union types in the signatures. We can change the style to be more fns w/ more explicit signatures. Either way we should document the preferred style to help consistency.

For now I think it's best to overload, but as @mikeringrose suggested, only w/ `IModel`. That way having `getContentFromPortal()` take a `string | IItem` is consistent.

> split these lines from the existing getContent function into their own enrichContent function that can be used at the end of both branches (getContentById and getContent).

I like that idea.

**Comment by mikeringrose** [comment]
@andrewctate naming the function `getContentById` would be a breaking API change. i'm not a big fan of union types because it introduces branching in the code, which raises the complexity. Since this is the pattern we've established, we should stick with it and possibly change on a major version bump. I would limit the type to just an IModel though, it makes the check a bit simpler.

**Comment by andrewctate** [comment]
@mikeringrose @tomwayson thank you both. In that case, I think the current POA looks like this:

- Change `getContent` call signature to accept an identifier or an `IModel` `getContent(idOrModel: string | IModel...)` [here](https://github.com/Esri/hub.js/blob/master/packages/content/src/content.ts#L71)
- Extract item and data objects from `idOrModel` as available
- If item object is available, use `getContentFromPortal`
- change `getContentFromPortal`
     - relax call signature to allow an item to be passed instead of an id: `getContentFromPortal(idOrItem: string | IItem,  requestOptions?: IHubRequestOptions)`
     - use item object when provided instead of requesting a new one from Portal API
- split [these lines](https://github.com/Esri/hub.js/blob/master/packages/content/src/content.ts#L90-L102) from the existing `getContent` function into their own `enrichContent` function to reduce complexity.
    - optionally accepts a `data` object: `enrichContent(data?: object)`
    - If `data` is provided, and `shouldFetchData` is true, register a function that resolves to a copy of the provided `model.data` hash instead of `getContentData` [here](https://github.com/Esri/hub.js/blob/master/packages/content/src/content.ts#L93)

**Comment by tomwayson** [comment]
LGTM, though, I'd say rather than have `enrichContent(content, data?: object)`, just do this `enrichContent({...content, data})` and then have that do `if (!content.data && shouldFetchData(content.hubType)) {`. I think that's simpler than resolving a promise, etc.
