### ISSUE TITLE
Consistent method prefix (fetch/lookup/get/search)

### ISSUE THREAD

**Issue by ajturner** [Esri/hub.js#60]
Currently, there are multiple synonymous method prefixes that conceptually mean the same:

`fetch` vs. `get` vs. `lookup` vs. `search`

For the developer user - can we choose one that applies to all "READ" type operations, even if the implementation requires more complex operations. For example, can `fetchInitiative` and `lookupSiteUrlByInitiative` become `getInitiative` and `getInitiativeSite`?

**Comment by tomwayson** [comment]
re: `fetchFoo` vs `getFoo`, see https://github.com/Esri/hub.js/issues/13#issuecomment-388932082

That said, I can tell from #56 that b/c the style we settled on is different than that of arcgis-rest-js and the Hub apps, it's going to be an uphill battle to enforce it, so I will concede and deprecate existing `fetchFoo()` fns in favor of their `getFoo()` equivalents.

In order to address the motivation behind the original decision, I propose that we don't use `getSyncFoo()` for sync methods that don't `GET` data, but instead use something like `syncFoo()`.

re: `lookup` vs `search`, those are 2 different operations so I think it makes sense to have 2 different prefixes.
