### ISSUE TITLE
createAnnotationService: add options

### ISSUE THREAD

**Issue by lisastaehli** [Esri/hub.js#99]
The `createAnnotationService` function only allows to add orgId and authentication (correct?). I would have expected to see more like `activateInitiative` where a name can be specified as well as a group.

We expect to have the annotation service also being analyzed/retrieved through ArcGIS Online in a first version of Urban, so it would be good to being able to give it a proper name.

**Comment by jgravois** [comment]
> The createAnnotationService function only allows to add orgId and authentication (correct?).

those are the definitely the required parameters. you can find a few more optional parameters in [`IRequestOptions`](https://esri.github.io/arcgis-rest-js/api/request/IRequestOptions/), but nothing that lets you specific a name or group for your hosted annotation service.

In ArcGIS Hub we currently only create one hosted feature service for comments/annotations for an Organization, regardless of how many initiatives they spin up. The schema of the table allows us to associate individual records with entities as general as an initiative, or an entire dataset an event or something as specific as proposing an edit to a specific feature in another service or replying to someone else's comment.

Because of this its been sufficient for us to hardcode the name of the new service as `hub_annotations`. since it is shared publicly (with editor tracking rules enabled that don't allow anonymous users to edit or remove existing posts, we aren't using Groups to manage permissions.

> We expect to have the annotation service also being analyzed/retrieved through ArcGIS Online

if you can explain in a little more detail what you'd like to see added/changed or removed, I'd love to hear it. Our team has gotten pretty creative at using [`typeKeywords`](https://github.com/Esri/hub.js/blob/48b0a2352f91a08bb93fad0bd81494a72e10147d/packages/annotations/src/create.ts#L117) to retrieve content via search, so thats definitely one options thats already available to you.

**Comment by jgravois** [comment]
> The createAnnotationService function only allows to add orgId and authentication (correct?).

Those are the required parameters, the only other things you can tack on can be found in [`IRequestOptions`](https://esri.github.io/arcgis-rest-js/api/request/IRequestOptions/).

> I would have expected to see a name can be specified as well as a group.

In ArcGIS Hub, we currently only create one hosted feature service to store annotations regardless of how many initiatives they spin up. The schema of the table allows you to associate a particular comment with something broad like a project or something very specific, like replying to another comment or proposing an edit to a feature in another service. Because the service is shared publicly (editor tracking disallows anonymous users from editing or deleting records), we don't manage sharing with Groups, but if you're interested in doing something like that, i'm happy to chat about it in more detail.

> We expect to have the annotation service also being analyzed/retrieved through ArcGIS Online

Can you explain in a little more detail what you'd need to accomplish that? Our team has gotten pretty creative using [`typeKeywords`](https://github.com/Esri/hub.js/blob/48b0a2352f91a08bb93fad0bd81494a72e10147d/packages/annotations/src/create.ts#L117) to surface our own content via search, so thats one option thats already available to you.

https://edn.maps.arcgis.com/sharing/rest/search?q=typekeywords:hubAnnotationLayer orgid:uCXeTVveQzP4IIcx&f=json

**Comment by jgravois** [comment]
> we decided that having one central Hub Annotations layer is fine for us for now as we can store target and source

fantastic. thats definitely what we envisioned.
